<a href="https://colab.research.google.com/github/ash030889/Portfolio_projects/blob/main/Social_network_ads__classification_project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Step - 1 Import the important libraries for the projects.
Here, we import numpy and pandas for loading and reading dataset and we import matplotlib.pyplot and seaborn for visualization.

In [137]:
import numpy as np
import pandas as pd
import seaborn as snr
import matplotlib.pyplot as plt

#Step - 2 Data gathering/ Data loading

In [191]:
# load dataset import csv file
data = pd.read_csv('/content/Social_Network_Ads.csv')

#Step - 3 Data Cleaning / Data preprocessing  

In [139]:
data.info() # get all information of dataset.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   User ID          400 non-null    int64 
 1   Gender           400 non-null    object
 2   Age              400 non-null    int64 
 3   EstimatedSalary  400 non-null    int64 
 4   Purchased        400 non-null    int64 
dtypes: int64(4), object(1)
memory usage: 15.8+ KB


In [140]:
data.head() # get top 5 rows of informations.

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In this step we need to clean data means we need to change Gender column's data into binary form and drop the User ID column.

In [141]:
#change Gender column into binary numbers.
data['Gender'] = data['Gender'].apply({'Female' : 0, 'Male' : 1}.get)

In [142]:
#delete the User ID column.
data.drop(['User ID'], axis = 1, inplace = True)

In [143]:
data.head()

Gender  Age  EstimatedSalary  Purchased
0       1   19            19000          0
1       1   35            20000          0
2       0   26            43000          0
3       0   27            57000          0
4       1   19            76000          0

#Step - 4 Clean Data - Divide into x (independent) and y (dependent)

In [144]:
#data division into independent and dependent.
x = data.drop(['Purchased'], axis = 1)
y = data['Purchased']

In [145]:
x.head()

Gender  Age  EstimatedSalary
0       1   19            19000
1       1   35            20000
2       0   26            43000
3       0   27            57000
4       1   19            76000

In [146]:
y.head()

0    0
1    0
2    0
3    0
4    0
Name: Purchased, dtype: int64

#Step - 5 Clean data spliting into training set and testing set

In [169]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y, train_size = 0.75)

#Step - 6 Using Knn for MLM

In [170]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors = 7)

In [171]:
knn.fit(x_train, y_train)

KNeighborsClassifier(n_neighbors=7)

#Step - 7 Predictions of dataset

In [172]:
predictions = knn.predict(x_test)

In [173]:
print(predictions)

[0 0 0 0 1 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 1 0 0 0 0 0 0 0
 1 0 0 1 1 0 1 1 0 1 0 0 0 1 1 0 0 0 0 0 0 0 0 1 0 1 0 1 0 1 0 1 0 1 0 1 1
 0 0 0 1 0 0 0 1 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0]


#Step - 8 Confusion matrix and Accuracy score

In [174]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, predictions)
ac = accuracy_score(y_test, predictions)

In [175]:
print(cm)
print(ac)

[[61  4]
 [13 22]]
0.83


In this knn MLM we can see that accuracy obtained is 83% which is quite good but we can try another models and get better accuracy.

#Using Logistic Regression MLM

In [176]:
from sklearn.linear_model import LogisticRegression
log_model = LogisticRegression()

In [177]:
log_model.fit(x_train, y_train)

LogisticRegression()

In [178]:
l_prediction = log_model.predict(x_test)

#Confusion matrix and Accuracy score

In [179]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, predictions)
ac = accuracy_score(y_test, predictions)

In [180]:
print(cm)
print(ac)

[[61  4]
 [13 22]]
0.83


In this Logistic Regression MLM we can see that accuracy obtained is 83% which is quite good and this accuracy is same as knn MLM but we can try another models and get better accuracy.



#Using Decision Tree MLM

In [181]:
from sklearn.tree import DecisionTreeClassifier
tree_model = DecisionTreeClassifier()

In [182]:
tree_model.fit(x_train,y_train)

DecisionTreeClassifier()

In [183]:
d_prediction = tree_model.predict(x_test)

#Confusion matrix and Accuracy score

In [184]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, predictions)
ac = accuracy_score(y_test, predictions)

In [185]:
print(cm)
print(ac)

[[61  4]
 [13 22]]
0.83


In this Decision Tree MLM we can see that accuracy obtained is 83% which is quite good and this accuracy is same as knn MLM and Logistic Regression MLM but we can try another models and get better accuracy.

#Using Random Forest MLM

In [186]:
from sklearn.ensemble import RandomForestClassifier
forest_model = RandomForestClassifier()

In [187]:
forest_model.fit(x_train, y_train)

RandomForestClassifier()

In [188]:
r_prediction = forest_model.predict(x_test)

#Confusion matrix and Accuracy score

In [189]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, predictions)
ac = accuracy_score(y_test, predictions)

In [190]:
print(cm)
print(ac)

[[61  4]
 [13 22]]
0.83



In this Random Forest MLM we can see that accuracy obtained is 83% which is quite good and this accuracy is same as previous three MLMs. So we can use any model for this dataset.

#Enter the new dataset for predict the purchasing status new user.

In [192]:
new_data = {'Gender' : 0,	'Age' : 25,	'EstimatedSalary' : 45000}
index = [1]
df = pd.DataFrame(new_data, index)
print(df)

   Gender  Age  EstimatedSalary
1       0   25            45000


In [193]:
new_prediction = forest_model.predict(df)
print(new_prediction)

[0]
